# Use the official HammerDB image as base
FROM tpcorg/hammerdb:latest

RUN apt-get update && apt-get install -y postgresql-client

# Copy your custom scripts into the image
COPY ./scripts/hammerdb /home/HammerDB-4.12/scripts/python/postgres/

# Copy your custom scripts into the image
COPY ./scripts/hammerdb/tprocc/pg_tprocc_py_DROP.sh /home/HammerDB-4.12/
COPY ./scripts/hammerdb/tprocc/pg_tprocc_py_TPCC_STANDARD.sh /home/HammerDB-4.12/
COPY ./scripts/hammerdb/tprocc/pg_tprocc_py_MORE_MULTI_COLUMN.sh /home/HammerDB-4.12/

COPY ./scripts/hammerdb/tproch/pg_tproch_py_DROP.sh /home/HammerDB-4.12/
