version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: exjobb-postgres-1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: benchmarkdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

    command: >
      postgres -c config_file=/etc/postgresql/postgresql.conf
               -c hba_file=/etc/postgresql/pg_hba.conf
    networks:
      - postgres-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d benchmarkdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - postgres-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin # Persistence volume
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-net

volumes:
  postgres-data:
  pgadmin-data: # Add this volume

networks:
  postgres-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
