version: "3.8"

services:
  postgres:
    image: exjobb-postgres:1.0
    container_name: exjobb-postgres-1
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin # Persistence volume
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-net

  hammerdb:
    #image: tpcorg/hammerdb:postgres
    image: exjobb-hammerdb:1.0

    platform: linux/amd64 # Required for M1/M2 Macs
    container_name: exjobb-hammerdb
    # volumes:
    #   - ./scripts/hammerdb:/home/HammerDB-4.12/custom_scripts # ✅ Replace default scripts
    networks:
      - postgres-net
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
  pgadmin-data: # Add this volume

networks:
  postgres-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
